version: '2'

services:
    http:
        image: nginx
        volumes:
            - ./:/usr/share/nginx/html/
            - ./build/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /usr/share/nginx/html/
        ports:
            - 8080:80
        depends_on:
            - php

    php:
        build: build/php
        env_file: .env
        volumes:
            - ./:/usr/share/nginx/html/
        working_dir: /usr/share/nginx/html/

    rabbitmq:
        image: rabbitmq:3.6
        env_file: .env

    composer:
        image: composer/composer:php5
        volumes:
            - ./:/usr/share/nginx/html/
        working_dir: /usr/share/nginx/html/

    database:
        image: mysql:5.6
        env_file: .env

    mail_worker:
        build: build/php
        env_file: .env
        volumes:
            - ./:/worker/
        working_dir: /worker/
        depends_on:
            - rabbitmq
        entrypoint: php scripts/mail_worker.php

